<?php  //[STAMP] f3daaa981f8e09926b04372014703764
namespace NSWDPC\Payments\NSWGOVCPP\Tests\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait FunctionalTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
