---
Name: nswdpc-cpp-configuration
---
NSWDPC\Payments\CPP\Configuration:
  # access token
  client_id: ''
  client_secret: ''
  # payment completion
  jwt_secret: ''
  # various URLs
  # where we get an access token from
  accesstoken_url: ''
  # where payments are taken
  gateway_url: ''
  # CPP refund request URL
  refund_url: ''
