---
Name: nswdpc-cpp-configuration
---
SilverStripe\Omnipay\Model\Payment:
  allowed_gateways:
    - 'NSWGOVCPP'
SilverStripe\Omnipay\GatewayInfo:
  NSWGOVCPP:
    parameters:
      clientId: ''
      clientSecret: ''
      jwtSecret: ''
      accessTokenUrl: ''
      requestPaymentUrl: ''
      gatewayUrl: ''
      refundUrl: ''
      testMode: false
---
Except:
  environment: 'live'
---
SilverStripe\Omnipay\Model\Payment:
  allowed_gateways:
    - 'Dummy'
---
Only:
  environment: 'live'
---
SilverStripe\Omnipay\GatewayInfo:
  NSWGOVCPP:
    parameters:
      testMode: false
